apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "isolution-mysql"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "isolution-redis"        